- alias: Halverlichting aan bij beweging en voordeur opening
  id: halverlichting_aan_bij_beweging_en_voordeur_opening

  trigger:
    - platform: state
      entity_id: binary_sensor.sensor_hal
      to: "on"

    - platform: state
      entity_id: binary_sensor.voordeur
      to: "on"

    - platform: state
      entity_id: binary_sensor.voorkamerdeur
      to: "on"

#  condition:
#    - condition: numeric_state
#      entity_id: sensor.sensor_hal_licht
#      below: 50
#
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 15

  action:
    - service: light.turn_on
      target:
        entity_id: light.verlichting_hal

- alias: voordeur lamp aan bij voordeur opening en beweging
  id: lamp_voordeur_aan_bij_beweging_en_voordeur_opening

  trigger:
    - platform: state
      entity_id: binary_sensor.sensor_hal
      to: "on"

    - platform: state
      entity_id: binary_sensor.voordeur
      to: "on"

    - platform: state
      entity_id: binary_sensor.voorkamerdeur
      to: "on"

#  condition:
#    - condition: numeric_state
#      entity_id: sensor.sensor_hal_licht
#      below: 40
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 15

  action:
    - service: light.turn_on
      target:
        entity_id: light.lamp_voordeur

- alias: Halverlichting uit na geen beweging
  id: halverlichting_uit_na_geen_beweging

  trigger:
    - platform: state
      entity_id: binary_sensor.sensor_hal
      to: "off"
      for: "00:05:00"

    - platform: state
      entity_id: binary_sensor.voorkamerdeur
      to: "off"
      for: "00:05:00"

  action:
    - service: light.turn_off
      target:
        entity_id: light.verlichting_hal

- alias: lamp voordeur uit na geen beweging
  id: lamp_voordeur_uit_na_geen_beweging

  trigger:
    - platform: state
      entity_id: binary_sensor.sensor_hal
      to: "off"
      for: "00:03:00"

    - platform: state
      entity_id: binary_sensor.voordeur
      to: "off"
      for: "00:03:00"

    - platform: state
      entity_id: binary_sensor.voorkamerdeur
      to: "off"
      for: "00:03:00"

  action:
    - service: light.turn_off
      target:
        entity_id: light.lamp_voordeur

#chatGPT: when light state changed to on, turn of after 10 minutes
- alias: verlichting hal countdown 15 minutes
  id: verlichting hal countdown 15 minutes

  trigger:
    - platform: state
      entity_id: light.verlichting_hal
      from: "off"
      to: "on"

  action:
    - delay: 00:15:00

    - service: light.turn_off
      target:
        entity_id: light.verlichting_hal

#chatGPT: when light state changed to on, turn of after 10 minutes
- alias: lamp voordeur countdown 15 minutes
  id: lamp voordeur countdown 15 minutes

  trigger:
    - platform: state
      entity_id: light.lamp_voordeur
      from: "off"
      to: "on"

  action:
    - delay: 00:15:00

    - service: light.turn_off
      target:
        entity_id: light.lamp_voordeur


